import Head from "next/head";
import { useQuery } from "react-query";
import { getIssues } from "../../services";
import config from "../../config.json";
import { useState } from "react";
import moment from "moment";
import Tab from "@/components/ages/tab";
import Cards from "@/components/ages/cards";
import { BarChart } from "@/components/ages/graph";
import Loading from "@/components/loading";

export default function Home() {
  const [active, setActive] = useState<{ index: number; title: string }>({
    title: config.age[0].title,
    index: 0,
  });
  const { data, isLoading } = useQuery({
    queryFn: getIssues,
    queryKey: ["fetched-issues"],
  });

  return (
    <>
      <Head>
        <title>Strata Security Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[100%] flex justify-center mx-auto max-w-5xl">
        <div className="mt-10 w-full">
          <div className="items-center flex gap-3 px-5 lg:px-0">
            <img
              className="rounded w-28 h-28"
              src="https://avatars.githubusercontent.com/u/15871264?s=200&v=4"
              alt="strataconsulting"
            />
            <div className="">
              <h1 className="text-lg text-gray-800 font-bold">
                Strata Security Dashboard
              </h1>
              <p className="text-sm text-gray-500">
                View the real-time status of your system&apos;s security and easily
                identify potential threats with our security dashboard&apos;s visual
                representation of all security activity.
              </p>
            </div>
          </div>
          <div className="container items-center px-4 py-8 m-auto mt-5">
            <div className="flex flex-wrap pb-3 mx-4 md:mx-24 lg:mx-0">
              <Tab
                active={active}
                setActive={setActive}
                loading={isLoading}
                error=""
                ages={data?.ages}
              />
              <Cards
                data={data?.ages[active.title]}
                active={active}
                error=""
                loading={isLoading}
              />
            </div>

            <BarChart data={data?.ages} loading={isLoading} />

            <Loading loading={isLoading} />
          </div>
        </div>
      </main>
    </>
  );
}
